// Realistic Medical Data Generated (Strictly curated)

const hospitals = [
    {
        "id": 1,
        "name": "AIIMS New Delhi",
        "city": "New Delhi",
        "type": "government",
        "totalBeds": 2200,
        "availableBeds": 383,
        "icuBeds": 330,
        "availableIcuBeds": 0,
        "emergencyBeds": 110,
        "mapLocation": "21.4041,80.5095",
        "emergencyFee": 0,
        "consultationFee": 40,
        "icuCost": 2000,
        "services": [
            "Surgery",
            "Emergency",
            "ICU",
            "Gastroenterology",
            "Radiology",
            "Gynecology",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-847-5981",
        "rating": 4.9
    },
    {
        "id": 2,
        "name": "Medanta - The Medicity",
        "city": "Gurugram",
        "type": "private",
        "totalBeds": 1250,
        "availableBeds": 63,
        "icuBeds": 187,
        "availableIcuBeds": 3,
        "emergencyBeds": 62,
        "mapLocation": "21.6320,82.6458",
        "emergencyFee": 700,
        "consultationFee": 2300,
        "icuCost": 8000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Endocrinology",
            "Gastroenterology",
            "Radiology",
            "Cardiology",
            "Gynecology",
            "Orthopedics",
            "Pulmonology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-338-7334",
        "rating": 4.8
    },
    {
        "id": 3,
        "name": "Apollo Hospitals, Greams Road",
        "city": "Chennai",
        "type": "private",
        "totalBeds": 560,
        "availableBeds": 56,
        "icuBeds": 84,
        "availableIcuBeds": 3,
        "emergencyBeds": 28,
        "mapLocation": "19.4540,78.9436",
        "emergencyFee": 1300,
        "consultationFee": 2400,
        "icuCost": 5000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Neurology",
            "Cardiology",
            "Pulmonology",
            "Gynecology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-463-3666",
        "rating": 4.7
    },
    {
        "id": 4,
        "name": "Christian Medical College (CMC)",
        "city": "Vellore",
        "type": "private",
        "totalBeds": 3000,
        "availableBeds": 397,
        "icuBeds": 450,
        "availableIcuBeds": 0,
        "emergencyBeds": 150,
        "mapLocation": "20.9876,83.5287",
        "emergencyFee": 500,
        "consultationFee": 1400,
        "icuCost": 5000,
        "services": [
            "Emergency",
            "Surgery",
            "Urology",
            "Endocrinology",
            "Gastroenterology",
            "Pediatrics",
            "Cardiology",
            "Pulmonology",
            "Orthopedics",
            "Nephrology",
            "Gynecology",
            "General Medicine"
        ],
        "emergencyContact": "1800-448-7279",
        "rating": 4.9
    },
    {
        "id": 5,
        "name": "Fortis Memorial Research Institute",
        "city": "Gurugram",
        "type": "private",
        "totalBeds": 1000,
        "availableBeds": 204,
        "icuBeds": 150,
        "availableIcuBeds": 1,
        "emergencyBeds": 50,
        "mapLocation": "27.5471,80.0211",
        "emergencyFee": 500,
        "consultationFee": 2300,
        "icuCost": 19000,
        "services": [
            "Emergency",
            "Surgery",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Pediatrics",
            "Neurology",
            "Cardiology",
            "Pulmonology",
            "ICU",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-972-5642",
        "rating": 4.6
    },
    {
        "id": 6,
        "name": "P. D. Hinduja National Hospital",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 400,
        "availableBeds": 24,
        "icuBeds": 60,
        "availableIcuBeds": 4,
        "emergencyBeds": 20,
        "mapLocation": "26.5600,75.5731",
        "emergencyFee": 1000,
        "consultationFee": 2500,
        "icuCost": 11000,
        "services": [
            "Surgery",
            "Emergency",
            "Oncology",
            "Urology",
            "Pediatrics",
            "Neurology",
            "Cardiology",
            "Gynecology",
            "Orthopedics",
            "Pulmonology",
            "Dermatology"
        ],
        "emergencyContact": "1800-352-7839",
        "rating": 4.7
    },
    {
        "id": 7,
        "name": "Lilavati Hospital and Research Centre",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 323,
        "availableBeds": 67,
        "icuBeds": 48,
        "availableIcuBeds": 1,
        "emergencyBeds": 16,
        "mapLocation": "27.2790,73.9452",
        "emergencyFee": 1200,
        "consultationFee": 900,
        "icuCost": 10000,
        "services": [
            "Emergency",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Radiology",
            "Pulmonology",
            "Gynecology",
            "General Medicine"
        ],
        "emergencyContact": "1800-949-2301",
        "rating": 4.6
    },
    {
        "id": 8,
        "name": "Tata Memorial Hospital",
        "city": "Mumbai",
        "type": "government",
        "totalBeds": 600,
        "availableBeds": 135,
        "icuBeds": 90,
        "availableIcuBeds": 0,
        "emergencyBeds": 30,
        "mapLocation": "27.4786,76.4566",
        "emergencyFee": 0,
        "consultationFee": 30,
        "icuCost": 1300,
        "services": [
            "Emergency",
            "Urology",
            "Oncology",
            "Gastroenterology",
            "Gynecology",
            "Pulmonology",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-488-6552",
        "rating": 4.8
    },
    {
        "id": 9,
        "name": "Kokilaben Dhirubhai Ambani Hospital",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 750,
        "availableBeds": 139,
        "icuBeds": 112,
        "availableIcuBeds": 5,
        "emergencyBeds": 37,
        "mapLocation": "23.1693,82.7812",
        "emergencyFee": 600,
        "consultationFee": 2100,
        "icuCost": 11000,
        "services": [
            "Emergency",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Neurology",
            "Radiology",
            "Gynecology",
            "ICU",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-473-3285",
        "rating": 4.7
    },
    {
        "id": 10,
        "name": "Narayana Health City",
        "city": "Bengaluru",
        "type": "private",
        "totalBeds": 1240,
        "availableBeds": 226,
        "icuBeds": 186,
        "availableIcuBeds": 2,
        "emergencyBeds": 62,
        "mapLocation": "21.7368,80.3107",
        "emergencyFee": 800,
        "consultationFee": 2000,
        "icuCost": 17000,
        "services": [
            "Emergency",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Pulmonology",
            "Orthopedics",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-363-6562",
        "rating": 4.6
    },
    {
        "id": 11,
        "name": "Manipal Hospital, HAL Airport Road",
        "city": "Bengaluru",
        "type": "private",
        "totalBeds": 600,
        "availableBeds": 67,
        "icuBeds": 90,
        "availableIcuBeds": 4,
        "emergencyBeds": 30,
        "mapLocation": "26.9635,74.6543",
        "emergencyFee": 900,
        "consultationFee": 900,
        "icuCost": 17000,
        "services": [
            "Emergency",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Pediatrics",
            "Neurology",
            "Radiology",
            "Pulmonology",
            "Dermatology"
        ],
        "emergencyContact": "1800-282-5878",
        "rating": 4.5
    },
    {
        "id": 12,
        "name": "Max Super Speciality Hospital, Saket",
        "city": "New Delhi",
        "type": "private",
        "totalBeds": 500,
        "availableBeds": 125,
        "icuBeds": 75,
        "availableIcuBeds": 4,
        "emergencyBeds": 25,
        "mapLocation": "25.7127,81.5053",
        "emergencyFee": 600,
        "consultationFee": 1300,
        "icuCost": 9000,
        "services": [
            "Surgery",
            "Emergency",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Pediatrics",
            "Radiology",
            "Pulmonology",
            "Orthopedics",
            "ICU",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-602-8901",
        "rating": 4.5
    },
    {
        "id": 13,
        "name": "Sir Ganga Ram Hospital",
        "city": "New Delhi",
        "type": "private",
        "totalBeds": 675,
        "availableBeds": 130,
        "icuBeds": 101,
        "availableIcuBeds": 2,
        "emergencyBeds": 33,
        "mapLocation": "19.2346,77.1223",
        "emergencyFee": 1300,
        "consultationFee": 800,
        "icuCost": 6000,
        "services": [
            "Emergency",
            "Surgery",
            "Oncology",
            "Endocrinology",
            "Pediatrics",
            "Neurology",
            "Radiology",
            "Gynecology",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-262-9977",
        "rating": 4.6
    },
    {
        "id": 14,
        "name": "Artemis Hospital",
        "city": "Gurugram",
        "type": "private",
        "totalBeds": 400,
        "availableBeds": 58,
        "icuBeds": 60,
        "availableIcuBeds": 5,
        "emergencyBeds": 20,
        "mapLocation": "19.9091,79.1039",
        "emergencyFee": 1500,
        "consultationFee": 1200,
        "icuCost": 18000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Pediatrics",
            "Radiology",
            "Gynecology",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-512-4458",
        "rating": 4.5
    },
    {
        "id": 15,
        "name": "BLK Super Speciality Hospital",
        "city": "New Delhi",
        "type": "private",
        "totalBeds": 650,
        "availableBeds": 64,
        "icuBeds": 97,
        "availableIcuBeds": 1,
        "emergencyBeds": 32,
        "mapLocation": "27.3895,76.6685",
        "emergencyFee": 1100,
        "consultationFee": 800,
        "icuCost": 18000,
        "services": [
            "Emergency",
            "Endocrinology",
            "Pediatrics",
            "Cardiology",
            "Gynecology",
            "Pulmonology",
            "General Medicine"
        ],
        "emergencyContact": "1800-464-3432",
        "rating": 4.4
    },
    {
        "id": 16,
        "name": "Indraprastha Apollo Hospital",
        "city": "New Delhi",
        "type": "private",
        "totalBeds": 710,
        "availableBeds": 137,
        "icuBeds": 106,
        "availableIcuBeds": 0,
        "emergencyBeds": 35,
        "mapLocation": "22.3505,85.8715",
        "emergencyFee": 700,
        "consultationFee": 1800,
        "icuCost": 11000,
        "services": [
            "Emergency",
            "Pediatrics",
            "Neurology",
            "Cardiology",
            "Pulmonology",
            "Gynecology",
            "Orthopedics"
        ],
        "emergencyContact": "1800-387-9160",
        "rating": 4.6
    },
    {
        "id": 17,
        "name": "Gleneagles Global Health City",
        "city": "Chennai",
        "type": "private",
        "totalBeds": 1000,
        "availableBeds": 211,
        "icuBeds": 150,
        "availableIcuBeds": 1,
        "emergencyBeds": 50,
        "mapLocation": "22.2387,82.9838",
        "emergencyFee": 1400,
        "consultationFee": 2400,
        "icuCost": 19000,
        "services": [
            "Emergency",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Gynecology",
            "Pulmonology",
            "ICU",
            "Nephrology",
            "Dermatology"
        ],
        "emergencyContact": "1800-349-5805",
        "rating": 4.5
    },
    {
        "id": 18,
        "name": "Amrita Hospital",
        "city": "Kochi",
        "type": "private",
        "totalBeds": 1300,
        "availableBeds": 300,
        "icuBeds": 195,
        "availableIcuBeds": 5,
        "emergencyBeds": 65,
        "mapLocation": "20.1609,75.2758",
        "emergencyFee": 600,
        "consultationFee": 1100,
        "icuCost": 8000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Pulmonology",
            "Orthopedics",
            "ICU",
            "Dermatology"
        ],
        "emergencyContact": "1800-636-7695",
        "rating": 4.8
    },
    {
        "id": 19,
        "name": "Sri Ramachandra Medical Centre",
        "city": "Chennai",
        "type": "private",
        "totalBeds": 800,
        "availableBeds": 181,
        "icuBeds": 120,
        "availableIcuBeds": 4,
        "emergencyBeds": 40,
        "mapLocation": "23.6192,74.6017",
        "emergencyFee": 1200,
        "consultationFee": 2500,
        "icuCost": 6000,
        "services": [
            "Surgery",
            "Emergency",
            "Endocrinology",
            "Pediatrics",
            "Cardiology",
            "Gynecology",
            "General Medicine"
        ],
        "emergencyContact": "1800-470-5237",
        "rating": 4.6
    },
    {
        "id": 20,
        "name": "KIMS Hospital",
        "city": "Secunderabad",
        "type": "private",
        "totalBeds": 1000,
        "availableBeds": 50,
        "icuBeds": 150,
        "availableIcuBeds": 3,
        "emergencyBeds": 50,
        "mapLocation": "18.4307,77.8842",
        "emergencyFee": 1000,
        "consultationFee": 2200,
        "icuCost": 17000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Endocrinology",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Pulmonology",
            "Orthopedics",
            "ICU",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-150-9731",
        "rating": 4.5
    },
    {
        "id": 21,
        "name": "Aster CMI Hospital",
        "city": "Bengaluru",
        "type": "private",
        "totalBeds": 500,
        "availableBeds": 109,
        "icuBeds": 75,
        "availableIcuBeds": 2,
        "emergencyBeds": 25,
        "mapLocation": "22.7102,83.9589",
        "emergencyFee": 500,
        "consultationFee": 1100,
        "icuCost": 15000,
        "services": [
            "Emergency",
            "Urology",
            "Endocrinology",
            "Gastroenterology",
            "Gynecology",
            "Pulmonology",
            "ICU",
            "Orthopedics",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-588-1109",
        "rating": 4.6
    },
    {
        "id": 22,
        "name": "Yashoda Hospitals",
        "city": "Hyderabad",
        "type": "private",
        "totalBeds": 1200,
        "availableBeds": 272,
        "icuBeds": 180,
        "availableIcuBeds": 2,
        "emergencyBeds": 60,
        "mapLocation": "24.0577,76.1197",
        "emergencyFee": 1100,
        "consultationFee": 1300,
        "icuCost": 6000,
        "services": [
            "Emergency",
            "Oncology",
            "Gastroenterology",
            "Neurology",
            "Radiology",
            "Gynecology",
            "Pulmonology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-780-1590",
        "rating": 4.5
    },
    {
        "id": 23,
        "name": "Jaslok Hospital",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 350,
        "availableBeds": 63,
        "icuBeds": 52,
        "availableIcuBeds": 0,
        "emergencyBeds": 17,
        "mapLocation": "24.8024,74.8257",
        "emergencyFee": 800,
        "consultationFee": 900,
        "icuCost": 8000,
        "services": [
            "Emergency",
            "Oncology",
            "Pediatrics",
            "Cardiology",
            "Orthopedics",
            "ICU",
            "General Medicine"
        ],
        "emergencyContact": "1800-137-1194",
        "rating": 4.5
    },
    {
        "id": 24,
        "name": "Continental Hospitals",
        "city": "Hyderabad",
        "type": "private",
        "totalBeds": 750,
        "availableBeds": 60,
        "icuBeds": 112,
        "availableIcuBeds": 4,
        "emergencyBeds": 37,
        "mapLocation": "22.0116,85.8634",
        "emergencyFee": 1200,
        "consultationFee": 1500,
        "icuCost": 19000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Gastroenterology",
            "Pediatrics",
            "Neurology",
            "Pulmonology",
            "Orthopedics",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-952-6880",
        "rating": 4.4
    },
    {
        "id": 25,
        "name": "MIOT International",
        "city": "Chennai",
        "type": "private",
        "totalBeds": 1000,
        "availableBeds": 217,
        "icuBeds": 150,
        "availableIcuBeds": 5,
        "emergencyBeds": 50,
        "mapLocation": "24.8545,86.7069",
        "emergencyFee": 1300,
        "consultationFee": 2200,
        "icuCost": 15000,
        "services": [
            "Emergency",
            "Urology",
            "Pediatrics",
            "Radiology",
            "Orthopedics",
            "ICU",
            "Nephrology"
        ],
        "emergencyContact": "1800-427-5868",
        "rating": 4.5
    },
    {
        "id": 26,
        "name": "Saifee Hospital",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 250,
        "availableBeds": 52,
        "icuBeds": 37,
        "availableIcuBeds": 2,
        "emergencyBeds": 12,
        "mapLocation": "22.5116,83.2048",
        "emergencyFee": 1500,
        "consultationFee": 2000,
        "icuCost": 8000,
        "services": [
            "Emergency",
            "Surgery",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Pediatrics",
            "Cardiology",
            "Pulmonology",
            "Orthopedics",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-626-4383",
        "rating": 4.4
    },
    {
        "id": 27,
        "name": "CARE Hospitals",
        "city": "Hyderabad",
        "type": "private",
        "totalBeds": 450,
        "availableBeds": 97,
        "icuBeds": 67,
        "availableIcuBeds": 4,
        "emergencyBeds": 22,
        "mapLocation": "24.6613,79.1895",
        "emergencyFee": 1300,
        "consultationFee": 1700,
        "icuCost": 5000,
        "services": [
            "Emergency",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Pediatrics",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Gynecology",
            "Orthopedics",
            "ICU",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-462-7424",
        "rating": 4.5
    },
    {
        "id": 28,
        "name": "Columbia Asia Hospital",
        "city": "Bengaluru",
        "type": "private",
        "totalBeds": 200,
        "availableBeds": 48,
        "icuBeds": 30,
        "availableIcuBeds": 4,
        "emergencyBeds": 10,
        "mapLocation": "24.0604,84.8603",
        "emergencyFee": 1500,
        "consultationFee": 800,
        "icuCost": 17000,
        "services": [
            "Emergency",
            "Surgery",
            "Pediatrics",
            "Neurology",
            "Radiology",
            "Orthopedics",
            "General Medicine"
        ],
        "emergencyContact": "1800-561-8956",
        "rating": 4.4
    },
    {
        "id": 29,
        "name": "Nanavati Max Super Speciality Hospital",
        "city": "Mumbai",
        "type": "private",
        "totalBeds": 350,
        "availableBeds": 57,
        "icuBeds": 52,
        "availableIcuBeds": 1,
        "emergencyBeds": 17,
        "mapLocation": "21.7495,73.7426",
        "emergencyFee": 600,
        "consultationFee": 1300,
        "icuCost": 19000,
        "services": [
            "Surgery",
            "Emergency",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Pediatrics",
            "Neurology",
            "Orthopedics",
            "ICU",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-195-3397",
        "rating": 4.5
    },
    {
        "id": 30,
        "name": "Rajiv Gandhi Cancer Institute",
        "city": "New Delhi",
        "type": "private",
        "totalBeds": 302,
        "availableBeds": 41,
        "icuBeds": 45,
        "availableIcuBeds": 1,
        "emergencyBeds": 15,
        "mapLocation": "20.6765,81.3592",
        "emergencyFee": 700,
        "consultationFee": 1200,
        "icuCost": 10000,
        "services": [
            "Surgery",
            "Emergency",
            "Oncology",
            "Neurology",
            "Cardiology",
            "Pulmonology",
            "Gynecology",
            "ICU",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-295-5451",
        "rating": 4.7
    },
    {
        "id": 31,
        "name": "AIIMS Bhubaneswar",
        "city": "Bhubaneswar",
        "type": "government",
        "totalBeds": 1000,
        "availableBeds": 50,
        "icuBeds": 150,
        "availableIcuBeds": 5,
        "emergencyBeds": 50,
        "mapLocation": "25.2172,75.3368",
        "emergencyFee": 0,
        "consultationFee": 20,
        "icuCost": 900,
        "services": [
            "Emergency",
            "Surgery",
            "Oncology",
            "Urology",
            "Gastroenterology",
            "Neurology",
            "Radiology",
            "Orthopedics",
            "ICU",
            "General Medicine"
        ],
        "emergencyContact": "1800-436-7788",
        "rating": 4.8
    },
    {
        "id": 32,
        "name": "SCB Medical College and Hospital",
        "city": "Cuttack",
        "type": "government",
        "totalBeds": 2100,
        "availableBeds": 305,
        "icuBeds": 315,
        "availableIcuBeds": 5,
        "emergencyBeds": 105,
        "mapLocation": "19.1036,80.7015",
        "emergencyFee": 0,
        "consultationFee": 30,
        "icuCost": 800,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Endocrinology",
            "Pediatrics",
            "Cardiology",
            "Gynecology",
            "Pulmonology",
            "ICU",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-432-6553",
        "rating": 4.5
    },
    {
        "id": 33,
        "name": "AMRI Hospitals",
        "city": "Bhubaneswar",
        "type": "private",
        "totalBeds": 400,
        "availableBeds": 63,
        "icuBeds": 60,
        "availableIcuBeds": 3,
        "emergencyBeds": 20,
        "mapLocation": "25.9871,82.7758",
        "emergencyFee": 900,
        "consultationFee": 1200,
        "icuCost": 12000,
        "services": [
            "Emergency",
            "Surgery",
            "Oncology",
            "ICU",
            "Endocrinology",
            "Gastroenterology",
            "Radiology",
            "Cardiology",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-908-2904",
        "rating": 4.3
    },
    {
        "id": 34,
        "name": "Kalinga Institute of Medical Sciences (KIMS)",
        "city": "Bhubaneswar",
        "type": "private",
        "totalBeds": 1500,
        "availableBeds": 251,
        "icuBeds": 225,
        "availableIcuBeds": 5,
        "emergencyBeds": 75,
        "mapLocation": "18.2257,83.1623",
        "emergencyFee": 1200,
        "consultationFee": 1800,
        "icuCost": 12000,
        "services": [
            "Emergency",
            "Oncology",
            "ICU",
            "Endocrinology",
            "Gastroenterology",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Gynecology",
            "Pulmonology",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-548-3831",
        "rating": 4.6
    },
    {
        "id": 35,
        "name": "SUM Ultimate Medicare",
        "city": "Bhubaneswar",
        "type": "private",
        "totalBeds": 375,
        "availableBeds": 75,
        "icuBeds": 56,
        "availableIcuBeds": 5,
        "emergencyBeds": 18,
        "mapLocation": "22.1103,80.6936",
        "emergencyFee": 1100,
        "consultationFee": 1900,
        "icuCost": 11000,
        "services": [
            "Emergency",
            "Urology",
            "Gastroenterology",
            "Pediatrics",
            "Neurology",
            "Radiology",
            "Cardiology",
            "Gynecology",
            "Orthopedics"
        ],
        "emergencyContact": "1800-706-2998",
        "rating": 4.5
    },
    {
        "id": 36,
        "name": "Ashwini Hospital",
        "city": "Cuttack",
        "type": "private",
        "totalBeds": 250,
        "availableBeds": 18,
        "icuBeds": 37,
        "availableIcuBeds": 5,
        "emergencyBeds": 12,
        "mapLocation": "21.3319,85.0625",
        "emergencyFee": 1400,
        "consultationFee": 1300,
        "icuCost": 10000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Oncology",
            "Gastroenterology",
            "Pediatrics",
            "Cardiology",
            "Gynecology",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-183-9717",
        "rating": 4.2
    },
    {
        "id": 37,
        "name": "Tata Medica Hospital",
        "city": "Kalinganagar",
        "type": "private",
        "totalBeds": 200,
        "availableBeds": 32,
        "icuBeds": 30,
        "availableIcuBeds": 2,
        "emergencyBeds": 10,
        "mapLocation": "25.0803,84.1628",
        "emergencyFee": 1500,
        "consultationFee": 2000,
        "icuCost": 19000,
        "services": [
            "Emergency",
            "Urology",
            "Oncology",
            "ICU",
            "Endocrinology",
            "Gastroenterology",
            "Neurology",
            "Cardiology",
            "Pulmonology",
            "Nephrology",
            "Dermatology"
        ],
        "emergencyContact": "1800-481-3847",
        "rating": 4.4
    },
    {
        "id": 38,
        "name": "Apollo Hospitals",
        "city": "Bhubaneswar",
        "type": "private",
        "totalBeds": 350,
        "availableBeds": 51,
        "icuBeds": 52,
        "availableIcuBeds": 0,
        "emergencyBeds": 17,
        "mapLocation": "19.5767,86.7581",
        "emergencyFee": 1400,
        "consultationFee": 1800,
        "icuCost": 5000,
        "services": [
            "Surgery",
            "Emergency",
            "Urology",
            "Gastroenterology",
            "ICU",
            "Nephrology",
            "General Medicine"
        ],
        "emergencyContact": "1800-804-9152",
        "rating": 4.7
    },
    {
        "id": 39,
        "name": "Ispat General Hospital (IGH)",
        "city": "Rourkela",
        "type": "government",
        "totalBeds": 600,
        "availableBeds": 54,
        "icuBeds": 90,
        "availableIcuBeds": 5,
        "emergencyBeds": 30,
        "mapLocation": "24.5485,87.6799",
        "emergencyFee": 0,
        "consultationFee": 30,
        "icuCost": 1700,
        "services": [
            "Surgery",
            "Emergency",
            "Oncology",
            "Endocrinology",
            "Gastroenterology",
            "Neurology",
            "Orthopedics",
            "ICU",
            "Nephrology",
            "Dermatology",
            "General Medicine"
        ],
        "emergencyContact": "1800-523-8788",
        "rating": 4.3
    },
    {
        "id": 40,
        "name": "MKCG Medical College and Hospital",
        "city": "Berhampur",
        "type": "government",
        "totalBeds": 1200,
        "availableBeds": 198,
        "icuBeds": 180,
        "availableIcuBeds": 1,
        "emergencyBeds": 60,
        "mapLocation": "18.8721,85.3484",
        "emergencyFee": 0,
        "consultationFee": 20,
        "icuCost": 2000,
        "services": [
            "Emergency",
            "Oncology",
            "Urology",
            "Endocrinology",
            "Gastroenterology",
            "Pediatrics",
            "Neurology",
            "Cardiology",
            "Orthopedics",
            "Nephrology"
        ],
        "emergencyContact": "1800-266-9738",
        "rating": 4.2
    }
];

const doctors = [
    {
        "id": 1,
        "name": "Dr. Naresh Trehan, MBBS, MS, FRACS",
        "specialty": "Cardiology",
        "hospitalId": 2,
        "rating": 4.9,
        "experience": 40,
        "fee": 2500,
        "image": "https://ui-avatars.com/api/?name=Naresh+Trehan&background=random"
    },
    {
        "id": 2,
        "name": "Dr. Devi Prasad Shetty, MBBS, MS, FRCS",
        "specialty": "Cardiology",
        "hospitalId": 10,
        "rating": 4.9,
        "experience": 40,
        "fee": 2000,
        "image": "https://ui-avatars.com/api/?name=Devi+Shetty&background=random"
    },
    {
        "id": 3,
        "name": "Dr. Ashok Seth, MBBS, MD, FRCP",
        "specialty": "Cardiology",
        "hospitalId": 5,
        "rating": 4.8,
        "experience": 35,
        "fee": 2000,
        "image": "https://ui-avatars.com/api/?name=Ashok+Seth&background=random"
    },
    {
        "id": 4,
        "name": "Dr. Suresh H. Advani, MBBS, MD, FICP",
        "specialty": "Oncology",
        "hospitalId": 23,
        "rating": 4.8,
        "experience": 45,
        "fee": 2500,
        "image": "https://ui-avatars.com/api/?name=Suresh+Advani&background=random"
    },
    {
        "id": 5,
        "name": "Dr. Sandeep Vaishya, MBBS, MS, MCh (Neurosurgery)",
        "specialty": "Neurology",
        "hospitalId": 5,
        "rating": 4.7,
        "experience": 25,
        "fee": 1800,
        "image": "https://ui-avatars.com/api/?name=Sandeep+Vaishya&background=random"
    },
    {
        "id": 6,
        "name": "Dr. Arvinder Singh Soin, MBBS, MS, FRCS (Edin)",
        "specialty": "Gastroenterology",
        "hospitalId": 2,
        "rating": 4.8,
        "experience": 30,
        "fee": 2500,
        "image": "https://ui-avatars.com/api/?name=Arvinder+Soin&background=random"
    },
    {
        "id": 7,
        "name": "Dr. Randeep Guleria, MBBS, MD, DM (Pulmonology)",
        "specialty": "Pulmonology",
        "hospitalId": 2,
        "rating": 4.9,
        "experience": 32,
        "fee": 2000,
        "image": "https://ui-avatars.com/api/?name=Randeep+Guleria&background=random"
    },
    {
        "id": 8,
        "name": "Dr. B. K. Misra, MBBS, MS, MCh (Neuro)",
        "specialty": "Neurology",
        "hospitalId": 6,
        "rating": 4.8,
        "experience": 35,
        "fee": 2100,
        "image": "https://ui-avatars.com/api/?name=B.+Misra&background=random"
    },
    {
        "id": 9,
        "name": "Dr. T. S. Kler, MBBS, MD, DM (Cardiology)",
        "specialty": "Cardiology",
        "hospitalId": 5,
        "rating": 4.7,
        "experience": 30,
        "fee": 1800,
        "image": "https://ui-avatars.com/api/?name=T.+Kler&background=random"
    },
    {
        "id": 10,
        "name": "Dr. Yatin Mehta, MBBS, MD (Anaesthesia), FRCA",
        "specialty": "Emergency",
        "hospitalId": 2,
        "rating": 4.7,
        "experience": 35,
        "fee": 2000,
        "image": "https://ui-avatars.com/api/?name=Yatin+Mehta&background=random"
    },
    {
        "id": 11,
        "name": "Dr. Ambrish Mithal, MBBS, MD, DM (Endocrinology)",
        "specialty": "Endocrinology",
        "hospitalId": 12,
        "rating": 4.8,
        "experience": 35,
        "fee": 2000,
        "image": "https://ui-avatars.com/api/?name=Ambrish+Mithal&background=random"
    },
    {
        "id": 12,
        "name": "Dr. Prathap C. Reddy, MBBS, MD, FCCP, FICA",
        "specialty": "Cardiology",
        "hospitalId": 3,
        "rating": 5.0,
        "experience": 50,
        "fee": 3000,
        "image": "https://ui-avatars.com/api/?name=Prathap+Reddy&background=random"
    },
    {
        "id": 13,
        "name": "Dr. Harsh Mahajan, MBBS, MD (Radiodiagnosis)",
        "specialty": "Radiology",
        "hospitalId": 13,
        "rating": 4.7,
        "experience": 35,
        "fee": 1500,
        "image": "https://ui-avatars.com/api/?name=Harsh+Mahajan&background=random"
    },
    {
        "id": 14,
        "name": "Dr. Yash Gulati, MBBS, MS (Orthopaedics), MCh",
        "specialty": "Orthopedics",
        "hospitalId": 16,
        "rating": 4.7,
        "experience": 35,
        "fee": 1800,
        "image": "https://ui-avatars.com/api/?name=Yash+Gulati&background=random"
    },
    {
        "id": 15,
        "name": "Dr. Nandita Palshetkar, MBBS, MD (Obstetrics & Gynaecology)",
        "specialty": "Gynecology",
        "hospitalId": 7,
        "rating": 4.7,
        "experience": 30,
        "fee": 2500,
        "image": "https://ui-avatars.com/api/?name=Nandita+Palshetkar&background=random"
    },
    {
        "id": 16,
        "name": "Dr. Narmada Prasad Gupta, MBBS, MS, MCh (Urology)",
        "specialty": "Urology",
        "hospitalId": 2,
        "rating": 4.8,
        "experience": 40,
        "fee": 2200,
        "image": "https://ui-avatars.com/api/?name=Narmada+Gupta&background=random"
    },
    {
        "id": 17,
        "name": "Dr. S. K. Sarin, MBBS, MD, DM (Gastroenterology)",
        "specialty": "Gastroenterology",
        "hospitalId": 1,
        "rating": 4.9,
        "experience": 40,
        "fee": 500,
        "image": "https://ui-avatars.com/api/?name=S.+Sarin&background=random"
    },
    {
        "id": 18,
        "name": "Dr. Rajendra Badwe, MBBS, MS (General Surgery)",
        "specialty": "Oncology",
        "hospitalId": 8,
        "rating": 4.9,
        "experience": 35,
        "fee": 500,
        "image": "https://ui-avatars.com/api/?name=Rajendra+Badwe&background=random"
    },
    {
        "id": 19,
        "name": "Dr. J. P. Muliyil, MBBS, MD (Community Medicine)",
        "specialty": "General Medicine",
        "hospitalId": 4,
        "rating": 4.8,
        "experience": 40,
        "fee": 800,
        "image": "https://ui-avatars.com/api/?name=J.+Muliyil&background=random"
    },
    {
        "id": 20,
        "name": "Dr. Datteswar Hota, MBBS, MS (General Surgery), MCh (Urology)",
        "specialty": "Urology",
        "hospitalId": 32,
        "rating": 4.9,
        "experience": 38,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Datteswar+Hota&background=random"
    },
    {
        "id": 21,
        "name": "Dr. Bibhuti B Nayak, MBBS, MS, MCh (Plastic Surgery)",
        "specialty": "Surgery",
        "hospitalId": 32,
        "rating": 4.7,
        "experience": 30,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Bibhuti+Nayak&background=random"
    },
    {
        "id": 22,
        "name": "Dr. Deba Prasad Mohanty, MBBS, MD (Anaesthesiology)",
        "specialty": "Emergency",
        "hospitalId": 32,
        "rating": 4.8,
        "experience": 33,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Deba+Mohanty&background=random"
    },
    {
        "id": 23,
        "name": "Dr. Sura Kishore Mishra, MBBS, MD, DM (Cardiology)",
        "specialty": "Cardiology",
        "hospitalId": 32,
        "rating": 4.8,
        "experience": 35,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Sura+Mishra&background=random"
    },
    {
        "id": 24,
        "name": "Dr. Jyoti Patnaik, MBBS, MD (Pulmonary Medicine)",
        "specialty": "Pulmonology",
        "hospitalId": 32,
        "rating": 4.6,
        "experience": 28,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Jyoti+Patnaik&background=random"
    },
    {
        "id": 25,
        "name": "Dr. Sudhir Ranjan Pattanaik, MBBS, MD, DM (Endocrinology)",
        "specialty": "Endocrinology",
        "hospitalId": 32,
        "rating": 4.8,
        "experience": 32,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Sudhir+Pattanaik&background=random"
    },
    {
        "id": 26,
        "name": "Dr. Bidyut Kumar Das, MBBS, MD (General Medicine), Fellowship (Rheumatology)",
        "specialty": "General Medicine",
        "hospitalId": 32,
        "rating": 4.7,
        "experience": 46,
        "fee": 100,
        "image": "https://ui-avatars.com/api/?name=Bidyut+Das&background=random"
    },
    {
        "id": 27,
        "name": "Dr. Satyajit Sahu, MBBS, MD (Dermatology)",
        "specialty": "Dermatology",
        "hospitalId": 39,
        "rating": 4.7,
        "experience": 15,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Satyajit+Sahu&background=random"
    },
    {
        "id": 28,
        "name": "Dr. Ashit Bhusan Xess, MBBS, MD (Microbiology)",
        "specialty": "General Medicine",
        "hospitalId": 39,
        "rating": 4.5,
        "experience": 20,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Ashit+Xess&background=random"
    },
    {
        "id": 29,
        "name": "Dr. Rajya Bardhan Pattanaik, MBBS, MD (Internal Medicine)",
        "specialty": "General Medicine",
        "hospitalId": 39,
        "rating": 4.6,
        "experience": 25,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Rajya+Pattanaik&background=random"
    },
    {
        "id": 30,
        "name": "Dr. Narayan Prasad Sahoo, MBBS, MS (General Surgery)",
        "specialty": "Surgery",
        "hospitalId": 39,
        "rating": 4.8,
        "experience": 28,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Narayan+Sahoo&background=random"
    },
    {
        "id": 31,
        "name": "Dr. L.N. Tripathy, MBBS, MS, MCh (Neurosurgery)",
        "specialty": "Neurology",
        "hospitalId": 39,
        "rating": 4.9,
        "experience": 30,
        "fee": 150,
        "image": "https://ui-avatars.com/api/?name=L.N.+Tripathy&background=random"
    },
    {
        "id": 32,
        "name": "Dr. Ashutosh Biswas, MBBS, MD, FACP",
        "specialty": "General Medicine",
        "hospitalId": 31,
        "rating": 4.9,
        "experience": 30,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Ashutosh+Biswas&background=random"
    },
    {
        "id": 33,
        "name": "Dr. Gitanjali Batmanabane, MBBS, MD (Pharmacology)",
        "specialty": "General Medicine",
        "hospitalId": 31,
        "rating": 4.8,
        "experience": 35,
        "fee": 50,
        "image": "https://ui-avatars.com/api/?name=Gitanjali+Batmanabane&background=random"
    },
    {
        "id": 34,
        "name": "Dr. Subrat Kumar Acharya, MBBS, MD, DM (Gastroenterology)",
        "specialty": "Gastroenterology",
        "hospitalId": 34,
        "rating": 4.9,
        "experience": 40,
        "fee": 1000,
        "image": "https://ui-avatars.com/api/?name=Subrat+Acharya&background=random"
    },
    {
        "id": 35,
        "name": "Dr. Ramnath Misra, MBBS, MD (Clinical Immunology)",
        "specialty": "General Medicine",
        "hospitalId": 34,
        "rating": 4.8,
        "experience": 35,
        "fee": 800,
        "image": "https://ui-avatars.com/api/?name=Ramnath+Misra&background=random"
    },
    {
        "id": 36,
        "name": "Dr. Ashok Kumar Mahapatra, MBBS, MS, MCh (Neurosurgery)",
        "specialty": "Neurology",
        "hospitalId": 35,
        "rating": 5.0,
        "experience": 42,
        "fee": 1500,
        "image": "https://ui-avatars.com/api/?name=Ashok+Mahapatra&background=random"
    },
    {
        "id": 37,
        "name": "Dr. Chandrika Prasad Das, MBBS, MD, DM (Cardiology)",
        "specialty": "Cardiology",
        "hospitalId": 33,
        "rating": 4.7,
        "experience": 28,
        "fee": 1200,
        "image": "https://ui-avatars.com/api/?name=Chandrika+Das&background=random"
    },
    {
        "id": 38,
        "name": "Dr. B. N. Mohapatra, MBBS, MD (General Medicine)",
        "specialty": "General Medicine",
        "hospitalId": 33,
        "rating": 4.6,
        "experience": 35,
        "fee": 1000,
        "image": "https://ui-avatars.com/api/?name=B.+Mohapatra&background=random"
    },
    {
        "id": 39,
        "name": "Dr. J.K. Dash, MBBS, MD (Pediatrics)",
        "specialty": "Pediatrics",
        "hospitalId": 35,
        "rating": 4.6,
        "experience": 25,
        "fee": 800,
        "image": "https://ui-avatars.com/api/?name=J.K.+Dash&background=random"
    },
    {
        "id": 40,
        "name": "Dr. Samir Sahu, MBBS, MD (Critical Care)",
        "specialty": "Emergency",
        "hospitalId": 35,
        "rating": 4.8,
        "experience": 22,
        "fee": 1000,
        "image": "https://ui-avatars.com/api/?name=Samir+Sahu&background=random"
    },
    {
        "id": 41,
        "name": "Dr. Banambar Ray, MBBS, MD (Critical Care)",
        "specialty": "Emergency",
        "hospitalId": 38,
        "rating": 4.9,
        "experience": 38,
        "fee": 1200,
        "image": "https://ui-avatars.com/api/?name=Banambar+Ray&background=random"
    }
];

const vaccinationCenters = [
    {
        "id": 1,
        "name": "AIIMS New Delhi Immunization Center",
        "location": "New Delhi",
        "vaccines": [
            "Covishield",
            "Covaxin",
            "Polio",
            "BCG",
            "HPV"
        ],
        "schedule": "Mon-Sat, 9AM - 4PM",
        "availability": "High"
    },
    {
        "id": 2,
        "name": "Apollo Main Vaccination Hub",
        "location": "Chennai",
        "vaccines": [
            "Covishield",
            "Covaxin",
            "Hepatitis B",
            "Typhoid",
            "Flu"
        ],
        "schedule": "Mon-Fri, 9AM - 5PM",
        "availability": "Medium"
    },
    {
        "id": 3,
        "name": "Fortis Escorts Prevention Clinic",
        "location": "Gurugram",
        "vaccines": [
            "Covaxin",
            "Flu",
            "Tetanus",
            "Pneumococcal"
        ],
        "schedule": "Everyday, 10AM - 2PM",
        "availability": "High"
    },
    {
        "id": 4,
        "name": "KIMS Urban Health & Vaccine Center",
        "location": "Secunderabad",
        "vaccines": [
            "Polio",
            "BCG",
            "Hepatitis A & B",
            "Rotavirus"
        ],
        "schedule": "Mon-Sat, 8AM - 1PM",
        "availability": "Low"
    }
];

// Helper functions for data access
const getHospitals = () => hospitals;
const getHospitalById = (id) => hospitals.find(h => h.id === parseInt(id));
const getDoctors = () => doctors;
const getDoctorsByHospital = (hospitalId) => doctors.filter(d => d.hospitalId === parseInt(hospitalId));
const getVaccinationCenters = () => vaccinationCenters;

// To allow use in regular script tag as well as module
if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = { hospitals, doctors, vaccinationCenters, getHospitals, getHospitalById, getDoctors, getDoctorsByHospital, getVaccinationCenters };
}
